domain: 'api.nlib.cc'
app-host: '0.0.0.0'
app-port: 80
database-path: '/data/NX-DB'
update-source: 'ghost-land/Nlib-API'
update-hour: 5                  # Hour to perform the update (24-hour format)
auto-update-enabled: true       # Enable or disable auto update
auto-update-on-startup: true   # Enable or disable auto update on startup

limiter-enabled: true
rate-limit: 5                   # Number of requests
rate-limit-period: 1            # Time period in seconds